### ISSUE TITLE
GC_correct error

### ISSUE THREAD

**Issue by missaileen** [molgenis/NIPTeR#20]
I am new to NIPTeR and just working through the flow  as per the Additional File 1 document of the paper.  All seemed to be going smoothly until I got to the gc correction of the control group.  I am getting the following error: 

bingc_control_group <- gc_correct(nipt_object = NIPT_control_group_separate, method = "bin")
Error in if (sum(reads != 0)) { : 
  argument is not interpretable as logical

Would you have any suggestions on how to get around this?  

Thanking you for your time,

**Comment by ljohansson** [comment]
This seems to be the same issue as: https://github.com/molgenis/NIPTeR/issues/18
Are you getting the error in the example data or in data procuced from bam files in other sampels?
Does the LOESS GC correction also give such an error?

**Comment by missaileen** [comment]
I was getting the error using my own data for both LOESS and bin methods. In the end it was my mistake- i did not set the ref-genome parameter to hg38, once this was done the issue resolved and I was able to proceed.  Thank you

**Comment by ljohansson** [comment]
Good to hear. Thanks for letting is know.

**Comment by Hafsah35** [comment]
Hallo, I got the same issue with @missaileen and I changed the reference genome to hg38, but I got a new issue 

> sample_of_interest <- gc_correct(nipt_object = sample_of_interest, method = "bin")
Error in gc_correct(nipt_object = sample_of_interest, method = "bin") : 
  object 'NIPT_sample_class' not found

what should I do to fix this thing? @ljohansson
