### ISSUE TITLE
How To Cite...?

### ISSUE THREAD

**Issue by VivekTodur** [molgenis/NIPTeR#6]
Hi..
Is this tools published...? how about the sensitivity of this tool.. Could you please some stats...

**Comment by ljohansson** [comment]
Hi VivekTodur,

We are currently in the process of publishing the new methods used in NIPTeR (just accepted this week).
The sensitivity depends on the exact methods used and on your dataset. However, for highest sensitivity, I would recommend to preprocess the data using GC correction and the chi_correction and then perform the prediction using the normalized chromosome value or the regression-based Z-score.

**Comment by ljohansson** [comment]
NIPTeR methods are now described in our paper.

Johansson, L.F, de Boer, E.N., de Weerd, H.A., van Dijk, F., Elferink, M.G., Schuring-Blom, G.H., Suijkerbuijk, R.F., Sinke, R.J., te Meerman G.J., Sijmons, R.H., Swertz, M.A. and Sikkema-Raddatz, B. “Novel Algorithms for Improved Sensitivity in Non-Invasive Prenatal Testing,” Sci. Rep., vol. 7, no. 1, p. 1838, 2017.

**Comment by VivekTodur** [comment]
That's wonderful... I am on way to testing it for our lab...

Warm Regards,
Vivek
