### ISSUE TITLE
Is there any document about the "sysdata.rda" file ? 

### ISSUE THREAD

**Issue by pl618** [molgenis/NIPTeR#7]
Hello,
Is there any document about the "sysdata.rda" file ? 
Would you like to give me some code/method on how to make these tables ?

Thanks.

**Comment by ljohansson** [comment]
We do not have a document about the sysdata.rda.
We are planning to work on a fix to enable use of custom gc_percentage tables.

**Comment by pl618** [comment]
Many thanks for your works.
