### ISSUE TITLE
Best practice pipeline ?

### ISSUE THREAD

**Issue by pl618** [molgenis/NIPTeR#8]
Hi, the vignette (https://cran.r-project.org/web/packages/NIPTeR/vignettes/NIPTeR.html)  has a workflow showed in figure 3.  This pipeline works good on my test data. However, the pipeline discussed on the paper is  slightly different.

The main difference is  the order of Chi-VR and match-QC.

so, which one is better ? or what is the best  practice pipeline besides these workflows ?

Thanks.

**Comment by sounkou-bioinfo** [comment]
hi @plsysu , did you settle on a stragety for the ordering of thse match QC ?
